name: CMake

on:
  push:
    branches: [ master ]
    paths:
      - 'python/setup.py'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_ubuntu:
    strategy:
        matrix:
          include:
            - runner: ubuntu-22.04
              artifact_name: wheel_ubuntu
            - runner: ubuntu-22.04-arm
              artifact_name: wheel_ubuntu_arm

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v7
      with:    
        submodules: true
    
    - name: Create Dir build_python
      run: mkdir build_python
      
    - name: Configure CMake      
      working-directory: ./build_python
      run: cmake -DCMAKE_CXX_FLAGS="-include cstdio" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ../python

    - name: Make
      working-directory: ./build_python    
      run: make
      
    - name: Make Install
      working-directory: ./build_python
      run: make install

    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: 3.14
    
    - name: Install dependencies
      run: pip install setuptools wheel twine

    - name: run setup.py
      working-directory: ./install/test_python
      run: python setup.py bdist_wheel

    - name: Twine upload
      working-directory: ./install/test_python/dist
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload *.whl    

  build_windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v7
        with:    
          submodules: true
          
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Create Dir build_python
        run: mkdir build_python
        
      - name: Configure CMake      
        working-directory: ./build_python
        run: cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ../python
        
      - name: Make
        working-directory: ./build_python    
        run: nmake

      - name: Make Install
        working-directory: ./build_python
        run: nmake install        

      - name: Set up Python 3.8
        uses: actions/setup-python@v6
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: pip install setuptools wheel twine    
       
      - name: run setup.py
        working-directory: ./install/test_python
        run: python setup.py bdist_wheel

      - name: Twine upload
        working-directory: ./install/test_python/dist
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload *.whl    
