name: CMake

on:
  push:
    branches: [ master ]
    paths:
      - 'python/setup.py'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_ubuntu_latest:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v7
        with:    
          submodules: true
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v6
        with:
            python-version: '3.8'

      - name: Install dependencies
        run: pip install setuptools wheel    
       
      - name: run setup.py
        working-directory: ./python
        run: python setup.py bdist_wheel
        
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v7
        with:
          name: ubuntu_amd_wheels
          path: ./python/dist/*.whl

  build_ubuntu_latest_arm:
    runs-on: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v7
        with:    
          submodules: true
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v6
        with:
            python-version: '3.8'

      - name: Install dependencies
        run: pip install setuptools wheel    
       
      - name: run setup.py
        working-directory: ./python
        run: python setup.py bdist_wheel
        
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v7
        with:
          name: ubuntu_arm_wheels
          path: ./python/dist/*.whl

  build_windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v7
        with:    
          submodules: true
          
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v6
        with:
            python-version: '3.8'

      - name: Install dependencies
        run: pip install setuptools wheel    
       
      - name: run setup.py
        working-directory: ./python
        run: python setup.py bdist_wheel
        
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows_wheels
          path: ./python/dist/*.whl
