name: CMake

on:
  push:
    branches: [ master ]
    paths:
      - 'python/setup.py'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        include:
          - artifact_name: ubuntu_amd_wheels
            runner: ubuntu-22.04
            DCMAKE_CXX_FLAGS: '-DCMAKE_CXX_FLAGS="-include cstdio"'
          - artifact_name: ubuntu_arm_wheels
            runner: ubuntu-22.04-arm
            DCMAKE_CXX_FLAGS: '-DCMAKE_CXX_FLAGS="-include cstdio"'
          - artifact_name: windows_wheels
            runner: windows-2022
            DCMAKE_CXX_FLAGS: ''
    runs-on: ${{ matrix.runner }}
    
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - name: Create Dir build_python
        run: mkdir build_python
        
      - name: Configure CMake      
        working-directory: ./build_python
        run: cmake ${{ matrix.DCMAKE_CXX_FLAGS }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ../python

      - name: Make
        working-directory: ./build_python    
        run: make
        
      - name: Make Install
        working-directory: ./build_python
        run: make install

      - name: Set up Python 3.8
        uses: actions/setup-python@v6
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install setuptools wheel

      - name: run setup.py
        working-directory: ./python
        run: python setup.py bdist_wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact_name }}
          path: ./python/dist/*.whl
